[package]
name = "fuse-query"
version = "0.1.0"
description = "A Distributed Query Engine"
authors = ["BohuTANG <bohu@datafuse.dev>", "Peter <peter@datafuse.dev>", "Kevin <kevin@datafuse.dev>"]
license = "AGPL-3.0"
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2018"

[[bin]]
name = "fuse-query"
path = "src/bin/fuse-query.rs"

[dependencies]
arrow = {version = "5.0", features = ["simd"]}
async-trait = "0.1"
bincode = "1.3.1"
futures = "0.3"
log = "0.4"
msql-srv = "0.9"
num = "0.3"
num_cpus = "1.0"
paste = "^1.0"
pin-project-lite= "^0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlparser = "0.6"
simplelog = "0.7"
thiserror = "1.0"
tokio = { version = "0.3", features = ["macros", "rt", "rt-multi-thread", "stream", "signal", "sync"] }

[dev-dependencies]
criterion = "0.3"
pretty_assertions = "0.6"

[[bench]]
name = "bench_main"
harness = false

